lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

# lexik_jwt_authentication:
#     secret_key: '%env(APP_SECRET)%'
#     public_key: '%env(JWT_PUBLIC_KEY_PATH)%'
#     user_identity_field: username
